// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OktaIA.Web.Data;

#nullable disable

namespace OktaIA.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810172614_UsuarioVinculadoAEmpresa")]
    partial class UsuarioVinculadoAEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OktaIA.Web.Models.AdminAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrigemIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("OktaIA.Web.Models.AlertaUnificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtivoIp")
                        .HasColumnType("text");

                    b.Property<string>("AtivoNome")
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("ConectorId")
                        .HasColumnType("integer");

                    b.Property<string>("DadosBrutosJson")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IngeridoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("boolean");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusOrigem")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAfetado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "OcorridoEm");

                    b.HasIndex("ConectorId", "IdExterno")
                        .IsUnique();

                    b.ToTable("AlertasUnificados");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Iniciais")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OktaIA.Web.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AutorizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AutorizadoParaScan")
                        .HasColumnType("boolean");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MonitoramentoContinuo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Real")
                        .HasColumnType("boolean");

                    b.Property<int>("Saude")
                        .HasColumnType("integer");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TlsDias")
                        .HasColumnType("integer");

                    b.Property<string>("TlsStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UltimoScanEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UptimePercentual")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<int>("VulnsAltas")
                        .HasColumnType("integer");

                    b.Property<int>("VulnsBaixas")
                        .HasColumnType("integer");

                    b.Property<int>("VulnsCriticas")
                        .HasColumnType("integer");

                    b.Property<int>("VulnsMedias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("AtivosCount")
                        .HasColumnType("integer");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<bool>("Demo")
                        .HasColumnType("boolean");

                    b.Property<string>("Dominio")
                        .HasColumnType("text");

                    b.Property<int>("IncidentesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScoreRisco")
                        .HasColumnType("integer");

                    b.Property<string>("SetorEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetorPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusContrato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UptimePercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("UsuariosCount")
                        .HasColumnType("integer");

                    b.Property<int>("VulnsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Conector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LatenciaMs")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAuth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UltimoErroEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UltimoHealthCheckEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UltimoSyncEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlBase")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Slug")
                        .IsUnique();

                    b.ToTable("Conectores");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ContactChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactChannels");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuantidadeAtivos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("OktaIA.Web.Models.CredencialConector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConectorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RotacionadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SegredoCifrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId")
                        .IsUnique();

                    b.ToTable("CredenciaisConector");
                });

            modelBuilder.Entity("OktaIA.Web.Models.CursorSync", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConectorId")
                        .HasColumnType("integer");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItensNoUltimoSync")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UltimoSyncEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId", "Escopo")
                        .IsUnique();

                    b.ToTable("CursoresSync");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ExecucaoSync", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Automatico")
                        .HasColumnType("boolean");

                    b.Property<int>("ConectorId")
                        .HasColumnType("integer");

                    b.Property<string>("Erro")
                        .HasColumnType("text");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItensLidos")
                        .HasColumnType("integer");

                    b.Property<int>("ItensNovos")
                        .HasColumnType("integer");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId", "IniciadoEm");

                    b.ToTable("ExecucoesSync");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AiConfianca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiResumoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiResumoPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Analista")
                        .HasColumnType("text");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("EventosCount")
                        .HasColumnType("integer");

                    b.Property<string>("MitreCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NarrativaEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NarrativaPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("OktaIA.Web.Models.IncidentStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentSteps");
                });

            modelBuilder.Entity("OktaIA.Web.Models.IncidentTimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentTimelineEvents");
                });

            modelBuilder.Entity("OktaIA.Web.Models.InfraHealthSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CpuPct")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscoPct")
                        .HasColumnType("integer");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("integer");

                    b.Property<int>("RamPct")
                        .HasColumnType("integer");

                    b.Property<int>("RedePct")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InfraHealthSnapshots");
                });

            modelBuilder.Entity("OktaIA.Web.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "AreaKey")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ScanAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Automatico")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaScan")
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DetectadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severidade")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("TituloEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ScanAlertas");
                });

            modelBuilder.Entity("OktaIA.Web.Models.SecurityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alvo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrigemIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OrigemLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("OrigemLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("OrigemPaisCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrigemPaisNomeEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrigemPaisNomePt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CriadoEm");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoriaScan")
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Componente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cve")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Cvss")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<string>("Cwe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExposicaoEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExposicaoPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FonteScan")
                        .HasColumnType("boolean");

                    b.Property<string>("InstrucoesEn")
                        .HasColumnType("text");

                    b.Property<string>("InstrucoesPt")
                        .HasColumnType("text");

                    b.Property<int>("PrioridadeIa")
                        .HasColumnType("integer");

                    b.Property<string>("RecomendacaoEn")
                        .HasColumnType("text");

                    b.Property<string>("RecomendacaoPt")
                        .HasColumnType("text");

                    b.Property<string>("RiscoEn")
                        .HasColumnType("text");

                    b.Property<string>("RiscoPt")
                        .HasColumnType("text");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloPt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OktaIA.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OktaIA.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OktaIA.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OktaIA.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OktaIA.Web.Models.AlertaUnificado", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OktaIA.Web.Models.Conector", "Conector")
                        .WithMany()
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ApplicationUser", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Asset", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Conector", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.CredencialConector", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Conector", "Conector")
                        .WithOne("Credencial")
                        .HasForeignKey("OktaIA.Web.Models.CredencialConector", "ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("OktaIA.Web.Models.CursorSync", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Conector", "Conector")
                        .WithMany("Cursores")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ExecucaoSync", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Conector", "Conector")
                        .WithMany()
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Incident", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.IncidentStep", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Incident", "Incident")
                        .WithMany("Passos")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("OktaIA.Web.Models.IncidentTimelineEvent", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Incident", "Incident")
                        .WithMany("LinhaDoTempo")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("OktaIA.Web.Models.RolePermission", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OktaIA.Web.Models.ScanAlerta", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.SecurityEvent", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Vulnerability", b =>
                {
                    b.HasOne("OktaIA.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Conector", b =>
                {
                    b.Navigation("Credencial");

                    b.Navigation("Cursores");
                });

            modelBuilder.Entity("OktaIA.Web.Models.Incident", b =>
                {
                    b.Navigation("LinhaDoTempo");

                    b.Navigation("Passos");
                });
#pragma warning restore 612, 618
        }
    }
}
